services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api 
  #   hostname: api
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL} 
  #     PORT: ${PORT}
  #     FRONT_URL: ${FRONT_URL}
  #     API_KEY: ${API_KEY} 
  #     API_ENV: ${API_ENV}
  #     JWT_SECRET_KEY: ${JWT_SECRET_KEY}
  #     JWT_MAXAGE: ${JWT_MAXAGE}
  #     SMTP_SERVER: ${SMTP_SERVER}
  #     SMTP_PORT: ${SMTP_PORT}
  #     SMTP_USERNAME: ${SMTP_USERNAME}
  #     SMTP_PASSWORD: ${SMTP_PASSWORD}
  #     GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  #     RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
  #
  #   ports:
  #     - 9999:9999
  #
  #   env_file:
  #     - .env
  #   volumes:
  #     - cargo-cache:/usr/local/cargo/registry  
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   networks:
  #     - blog_network
        
  db:
    image: postgres:17
    container_name: postgres_db
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - blog_network

volumes:
  postgres_data:
  cargo-cache:

networks:
  blog_network:
    driver: bridge
