FROM rust:latest AS dev

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libpq-dev \
    pkg-config \
    ca-certificates \
    && apt-get clean

WORKDIR /app

COPY . .

RUN cargo install sqlx-cli --no-default-features --features postgres

RUN cargo fetch

CMD ["sleep", "infinity"]

